apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm: vm-centos9-datavolume
  name: vm-centos9-datavolume
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: centos9-dv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
      source:
        http: 
          url: "https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-GenericCloud-9-20220330.1.x86_64.qcow2" 
          secretRef: "" 
          certConfigMap: "" 
    status: {}
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/vm: vm-centos9-datavolume
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumedisk1
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: "" 
        resources:
          requests:
            memory: 1.5Gi
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: centos9-dv
        name: datavolumedisk1
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            user: cloud-user
            password: pass
            chpasswd:
              expire: false
        name: cloudinitdisk
status: {}